services:
  node1:
    build: .
    container_name: mpi-node1
    hostname: node1
    ports:
      - "2222:22"
    networks:
      mpi-net:
        ipv4_address: 172.28.1.1
    volumes:
      - ./shared_data:/home/mpiuser/mpi-data

  node2:
    build: .
    container_name: mpi-node2
    hostname: node2
    ports:
      - "2223:22"
    networks:
      mpi-net:
        ipv4_address: 172.28.1.2
    volumes:
      - ./shared_data:/home/mpiuser/mpi-data

  node3:
    build: .
    container_name: mpi-node3
    hostname: node3
    ports:
      - "2224:22"
    networks:
      mpi-net:
        ipv4_address: 172.28.1.3
    volumes:
      - ./shared_data:/home/mpiuser/mpi-data

networks:
  mpi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

